home/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('',views.home, name='home'),
    path('edit/<id>', views.edit, name='edit'),
    path('completed/<id>', views.completed, name='completed'),
    path('delete/<id>',views.delete, name='delete'),
    path('filter/<choice>/', views.filter_priority, name='priority'),
    path('status/<choice>/', views.filter_status, name='status'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
]

home/models.py
from django.db import models


class Task(models.Model):
    Priority = (('L', 'Low'),
                ('M', 'Medium'),
                ('H', 'High'))

    task_name = models.CharField(max_length=200)
    due_date = models.DateTimeField(default=None, null=True, blank=True)
    completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=1, choices=Priority, default='L')

    def __str__(self):
        return self.task_name

home/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task_name', 'due_date']


class UpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task_name', 'due_date', 'priority', 'completed']

home/views.py
from django.shortcuts import render, HttpResponse,redirect
from .models import Task
from .forms import TaskForm, UpdateForm


def home(request):
    if request.method=='POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:home')

    tasks= Task.objects.all()
    form = TaskForm()
    print(form)
    return render(request, 'home.html', {'tasks': tasks, 'form': form})


def edit(request, id=id):
    task = Task.objects.get(id=id)
    if request.method == 'POST':
        form = UpdateForm(request.POST or None, instance=task)
        if form.is_valid():
            form.save()
            return redirect('home:home')

    form = UpdateForm(request.POST or None, instance=task)
    print(form)
    return render(request, 'edit.html', {'form': form})


def completed(request, id):
    task = Task.objects.get(id=id)
    if task.completed != True:
        task.completed=True
        task.save()
        return redirect('home:home')


def delete(request, id):
    task = Task.objects.get(id=id)
    task.delete()
    return redirect('home:home')


def filter_priority(request, choice):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:home')

    tasks = Task.objects.filter(priority=choice)
    form = TaskForm()
    print(form)
    return render(request, 'home.html', {'tasks': tasks, 'form': form})


def filter_status(request, choice):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:home')

    tasks = Task.objects.filter(completed=choice)
    form = TaskForm()
    print(form)
    return render(request, 'home.html', {'tasks': tasks, 'form': form})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Todo-S</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Add Bootstrap classes-->
        <link rel="stylesheet"
         href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
         crossorigin="anonymous">
         <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
         integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
         crossorigin="anonymous"></script>
         <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"
         integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf"
          crossorigin="anonymous"></script>

          <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
           integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
            crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

            <!-- Popper JS -->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

            <!-- Latest compiled JavaScript -->
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Add CSS here -->
            <style>
                body{
                    font-family: 'Open-Sans', sans-serif;
                    line-height: 1.6;
                }
                .add-todo-input {
                    outline: None;
                }
            </style>
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

templates/edit.html
{% extends 'base.html' %}
{% block content %}
<div class="container  text-center m-5 p-2 rounded mx-auto bg-light shadow">

            <div class="row m-1 p-4">
                <div class="col">
                    <h3 class="card-header bg-info p-3 m-2 text-white ">Update Task </h3>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Update">
                    </form>
                </div>
            </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container m-5 p-2 rounded mx-auto bg-light shadow">

            <div class="row m-1 p-4">
                <div class="col">
                    <div class="p-1 h1 text-primary text-center display-inline-block">
                        <i class="fa fa-check bg-primary text-white p-2"></i>
                        <u>MY Todo-s</u>
                    </div>
                </div>
            </div>

            <!-- Create form -->
            <form method="POST">
                {% csrf_token %}

                <div class="row m-1 p-3">
                    <div class="col col-11 mx-auto">
                        <div class="row bg-white justify-content-center">
                            <div class="col">
                                <input type="text"  name="task_name" maxlength="200" required id="id_task_name"
                                 class="form-control form-control-lg border-0 add-todo-input bg-transparent " placeholder="Add New...">

                            </div>
                            <div class="col-auto m-0 px-2 d-flex align-items-center">
                                <input title="Set a due date" type="date" name="due_date" id="id_due_date">
                            </div>
                            <div class="col-auto px-0 mx-0 mr-2">
                                <input type="submit" class="btn btn-primary" value="Add" />
                            </div>
                        </div>
                    </div>
                </div>
            </form>

            <div class="p-2 mx-4 border-black-25 border-bottom" ></div>

            <!-- Add Task Table -->
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Task</th>
                        <th scope="col">
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle" type="button"
                                 data-toggle="dropdown">
                                Priority
                                </button>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" href="{% url 'home:home' %}">ALL</a>
                                        <a class="dropdown-item" href="{% url 'home:priority' 'L' %}">Low</a>
                                        <a class="dropdown-item" href="{% url 'home:priority' 'M' %}">Medium</a>
                                        <a class="dropdown-item" href="{% url 'home:priority' 'H' %}">High</a>

                                    </li>

                                </ul>
                            </div>
                        </th>
                        <th scope="col">Due Date</th>
                        <th scope="col">
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle" type="button"
                                 data-toggle="dropdown">
                                Status
                                </button>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" href="{% url 'home:home' %}">ALL</a>
                                        <a class="dropdown-item" href="{% url 'home:status' 'False' %}">Pending</a>
                                        <a class="dropdown-item" href="{% url 'home:status' 'True' %}">completed</a>

                                    </li>

                                </ul>
                            </div>
                        </th>

                    </tr>
                </thead>
                <tbody>
                {% for task in tasks %}
                    <tr>
                        <td scope="row">{{ forloop.counter }}</td>
                        <td scope="row">{{ task.task_name }}</td>
                        <td scope="row">{{ task.priority}}</td>
                        <td scope="row">{{ task.due_date}}</td>
                        <td scope="row">
                            {% if task.completed == True %}
                            Done
                            {% else %}
                            <a class="link" href="{% url 'home:completed' task.id %}">mark as complete</a>
                        {% endif %}
                        </td>
                        <td><a href="{% url 'home:edit' task.id %}"><i class="fa fa-edit text-primary"></i></a></td>
                        <td><a href="{% url 'home:delete' task.id%}"><i class="fa fa-trash text-danger"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>


{% endblock %}